[package]
name = "nx-logger"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A centralized, non-blocking observability utility for the Nexus framework featuring typestate configuration, automated field redaction, and optional OpenTelemetry (OTLP) tracing"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["logging", "tracing", "opentelemetry", "otlp", "observability"]
categories = ["development-tools::debugging", "api-bindings"]
publish = true

[features]
default = []
profiling = ["dep:console-subscriber", "dep:tracing-tracy"]
opentelemetry = [
    "dep:tracing-opentelemetry",
    "dep:opentelemetry",
    "dep:opentelemetry-appender-tracing",
    "dep:opentelemetry-otlp",
    "dep:opentelemetry_sdk"
]
metrics = [
    "opentelemetry",
    "opentelemetry_sdk/metrics",
    "opentelemetry-otlp/metrics",
]

[dependencies]
nx-error = { workspace = true, features = ["json"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "ansi", "json"] }
tracing.workspace = true
serde.workspace = true
fxhash.workspace = true
smol_str.workspace = true
smallvec.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
console-subscriber = { workspace = true, optional = true }
opentelemetry = { workspace = true, optional = true }
opentelemetry-appender-tracing = { workspace = true, optional = true }
opentelemetry-otlp = {
    workspace = true,
    optional = true,
    features = ["trace", "logs", "grpc-tonic", "zstd-tonic"]
}
opentelemetry_sdk = { workspace = true, optional = true, features = ["trace", "logs", "rt-tokio"] }
tracing-appender.workspace = true
tracing-opentelemetry = { workspace = true, optional = true }
tracing-tracy = {
    workspace = true,
    optional = true,
    features = ["flush-on-exit", "system-tracing", "sampling", "code-transfer"]
}

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio", "html_reports"] }
dhat.workspace = true
proptest.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }

[lib]
name = "nx_logger"
path = "src/lib.rs"

[[bench]]
name = "logger"
harness = false

[lints]
workspace = true