[package]
name = "nx-logger"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A centralized, non-blocking observability utility for the Nexus framework featuring typestate configuration, automated field redaction, and optional OpenTelemetry (OTLP) tracing"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["logging", "tracing", "opentelemetry", "otlp", "observability"]
categories = ["development-tools::debugging", "api-bindings"]
publish = true

[features]
default = []
profiling = ["console-subscriber"]
opentelemetry = [
    "dep:opentelemetry",
    "dep:tracing-opentelemetry",
    "dep:opentelemetry-appender-tracing",
    "dep:opentelemetry-otlp",
    "dep:opentelemetry_sdk",

    "opentelemetry-otlp/trace",
    "opentelemetry-otlp/logs",
    "opentelemetry-otlp/grpc-tonic",
    "opentelemetry-otlp/zstd-tonic",

    "opentelemetry_sdk/trace",
    "opentelemetry_sdk/logs",
    "opentelemetry_sdk/rt-tokio",
]
metrics = [
    "opentelemetry",
    "opentelemetry_sdk/metrics",
    "opentelemetry-otlp/metrics",
]

[dependencies]
nx-error = { workspace = true, features = ["json"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "ansi", "json"] }
tracing.workspace = true
serde.workspace = true
fxhash.workspace = true
smol_str.workspace = true
smallvec.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
console-subscriber = { workspace = true, optional = true }
opentelemetry = { workspace = true, optional = true }
opentelemetry-appender-tracing = { workspace = true, optional = true }
opentelemetry-otlp = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true, optional = true }
tracing-appender.workspace = true
tracing-opentelemetry = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio", "html_reports"] }
dhat.workspace = true
proptest.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }

[lib]
name = "nx_logger"
path = "src/lib.rs"

[[bench]]
name = "logger"
harness = false

[lints]
workspace = true