[package]
name = "nx-organization"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Organization component"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["wasm", "spin", "fermyon"]
categories = []
publish.workspace = true

[package.metadata.service]
route = "/org"
access = "private"
depends_on = ["nx-audit"]

[package.metadata.service.spin]
allowed_outbound_hosts = ["{{ database_url }}"]

[package.metadata.service.spin.variables]
database_url = "{{ database_url }}"

[package.metadata.service.spin.environment]

[dependencies]
nx-http = { workspace = true, features = ["spin"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
utoipa.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "nx_organization"
path = "src/lib.rs"

[lints]
workspace = true
