events {
    worker_connections 1024;
}

http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 8080;
        resolver 127.0.0.11 valid=30s ipv6=off;

        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        # 1. Static resources
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        # 2. Spin API
        location /api/ {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_pass_header DPoP;
            proxy_pass_header Authorization;
        }

        # 3. SurrealDB (RPC & HTTP)
        location /surrealdb/ {
            set $surrealdb http://surrealdb:8000;
            rewrite ^/surrealdb/(.*) /$1 break;
            proxy_pass $surrealdb;
        }

        # 4. Grafana (UI)
        location /grafana/ {
            set $grafana http://grafana:3000;
            proxy_pass $grafana;
        }

        # 5. MinIO Console (UI)
        location /minio/ {
            set $minio_console http://minio:9001;
            rewrite ^/minio/(.*) /$1 break;
            proxy_pass $minio_console;
            proxy_set_header Host $http_host;
        }
    }
}