[package]
name = "nx-auth"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Auth component"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["wasm", "spin", "fermyon"]
categories = []
publish.workspace = true

[package.metadata.service]
route = "/api/auth"
access = "public"

[package.metadata.service.spin]
allowed_outbound_hosts = ["{{ redis_url }}", "{{ database_url }}"]

[package.metadata.service.spin.variables]
redis_url = "{{ redis_url }}"
database_url = "{{ database_url }}"
database_namespace = "{{ database_namespace }}"
database_name = "{{ database_name }}"

[package.metadata.service.spin.environment]

[dependencies]
nx-http = { workspace = true, features = ["spin"] }
nx-database.workspace = true
serde.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
utoipa.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
name = "nx_auth"
path = "src/lib.rs"

[lints]
workspace = true
